---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      day: "wednesday"
      interval: "weekly"
      time: "18:10"
      timezone: "Europe/London"
    target-branch: "main"
    commit-message:
      prefix: "fix:"
    open-pull-requests-limit: 5
