---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  gather-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/writeMetadata.yml@main
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  docker-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerLint.yml@main
    with:
      dockerfilePath: 'docker/Dockerfile'
  docker-build:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerBuild.yml@main
    with:
      dockerfilePath: 'docker/Dockerfile'
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      token: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [gather-metadata, docker-lint]
