---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  gather-metadata:
    uses: GrabAByte/github-devops-workflows/.github/workflows/writeMetadata.yml@feat/versionBump
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  docker-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerLint.yml@main
    with:
      dockerfilePath: 'docker/Dockerfile'
    needs: gather-metadata
  docker-build:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerBuild.yml@feat/main
    with:
      dockerfilePath: 'docker/Dockerfile'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: docker-lint
