---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  get-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/getVersion.yml@main
    with:
      metadataFile: 'metadata.json'
      metadataPath: .
  docker-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerLint.yml@main
    with:
      dockerfilePath: 'docker/Dockerfile'
    needs: get-version
  docker-build-publish:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerBuild.yml@main
    with:
      dockerfilePath: 'docker/Dockerfile'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: docker-lint
  update-version:
    uses: GrabAByte/github-devops-workflows/.github/workflows/updateVersion.yml@main
    with:
      gitUsername: 'grababyte'
      gitEmail: 'grababyte@github.com'
      metadataFile: 'metadata.json'
      metadataPath: .
    needs: docker-build-publish
