---

name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerLint.yml@feat/shareVars
  docker-build:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerBuild.yml@main
