---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  if: ${{ github.actor == 'dependabot[bot]' }}
  docker-lint:
    uses: GrabAByte/github-devops-workflows/.github/workflows/dockerLint.yml@0.3.0
    with:
      dockerfilePath: 'docker/Dockerfile'
    needs: get-version
